-- Create table for storing sage onboarding data
CREATE TABLE IF NOT EXISTS sage_onboarding_data (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  form_data JSONB NOT NULL,
  lab_file_analysis JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create table for storing generated nutrition plans
CREATE TABLE IF NOT EXISTS sage_nutrition_plans (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  plan_data JSONB NOT NULL,
  generated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  version INTEGER DEFAULT 1,
  FOREIGN KEY (email) REFERENCES sage_onboarding_data(email) ON DELETE CASCADE
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_sage_onboarding_email ON sage_onboarding_data(email);
CREATE INDEX IF NOT EXISTS idx_sage_plans_email ON sage_nutrition_plans(email);
CREATE INDEX IF NOT EXISTS idx_sage_plans_generated_at ON sage_nutrition_plans(generated_at DESC);

-- Create updated_at trigger for sage_onboarding_data
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_sage_onboarding_updated_at
  BEFORE UPDATE ON sage_onboarding_data
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Add comments for documentation
COMMENT ON TABLE sage_onboarding_data IS 'Stores user onboarding responses from the sage nutrition onboarding flow';
COMMENT ON TABLE sage_nutrition_plans IS 'Stores AI-generated personalized nutrition plans';
COMMENT ON COLUMN sage_onboarding_data.form_data IS 'Complete onboarding form data including personal info, goals, health baseline, fitness, and nutrition preferences';
COMMENT ON COLUMN sage_onboarding_data.lab_file_analysis IS 'AI analysis results from uploaded lab/bloodwork files';
COMMENT ON COLUMN sage_nutrition_plans.plan_data IS 'Complete nutrition plan generated by AI including executive summary, biomarkers, recommendations, meal plans';
